[workspace]
resolver = "2"

members = [
    "emu",
    "nes"
]

default-members = ["emu"]

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

# [profile.release.overrides.emu]
# opt-level = 1
