use super::{
    address_mode::{AddrFn, AddrMode},
    instructions::{Instruction, OperFn},
};

use AddrMode::*;
use Instruction::*;

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct InstructionSet {
    pub op: Instruction,
    pub am: AddrMode,
    pub cc: u8,
}

impl InstructionSet {
    pub const fn new(ins: Instruction, am: AddrMode, cycles: u8) -> Self {
        Self {
            op: ins,
            am,
            cc: cycles,
        }
    }
}

pub struct Operation {
    pub op: Instruction,
    pub am: AddrMode,
    pub cc: u8,
    pub op_fn: OperFn,
    pub am_fn: AddrFn,
}

impl Default for Operation {
    fn default() -> Self {
        Self {
            op: Instruction::ADC,
            am: AddrMode::ABS,
            cc: 2,
            op_fn: Instruction::ADC.into(),
            am_fn: AddrMode::ABS.into(),
        }
    }
}

impl From<InstructionSet> for Operation {
    fn from(value: InstructionSet) -> Self {
        Self {
            op: value.op,
            am: value.am,
            cc: value.cc,
            op_fn: value.op.into(),
            am_fn: value.am.into(),
        }
    }
}

pub const OPERATIONS: [InstructionSet; 256] = [
    InstructionSet::new(BRK, IMM, 7),
    InstructionSet::new(ORA, IZX, 6),
    InstructionSet::new(XXX, IMP, 2),
    InstructionSet::new(XXX, IMP, 8),
    InstructionSet::new(NOP, IMP, 3),
    InstructionSet::new(ORA, ZPG, 3),
    InstructionSet::new(ASL, ZPG, 5),
    InstructionSet::new(XXX, IMP, 5),
    InstructionSet::new(PHP, IMP, 3),
    InstructionSet::new(ORA, IMM, 2),
    InstructionSet::new(ASL, IMP, 2),
    InstructionSet::new(XXX, IMP, 2),
    InstructionSet::new(NOP, IMP, 4),
    InstructionSet::new(ORA, ABS, 4),
    InstructionSet::new(ASL, ABS, 6),
    InstructionSet::new(XXX, IMP, 6),
    InstructionSet::new(BPL, REL, 2),
    InstructionSet::new(ORA, IZY, 5),
    InstructionSet::new(XXX, IMP, 2),
    InstructionSet::new(XXX, IMP, 8),
    InstructionSet::new(NOP, IMP, 4),
    InstructionSet::new(ORA, ZPX, 4),
    InstructionSet::new(ASL, ZPX, 6),
    InstructionSet::new(XXX, IMP, 6),
    InstructionSet::new(CLC, IMP, 2),
    InstructionSet::new(ORA, ABY, 4),
    InstructionSet::new(NOP, IMP, 2),
    InstructionSet::new(XXX, IMP, 7),
    InstructionSet::new(NOP, IMP, 4),
    InstructionSet::new(ORA, ABX, 4),
    InstructionSet::new(ASL, ABX, 7),
    InstructionSet::new(XXX, IMP, 7),
    InstructionSet::new(JSR, ABS, 6),
    InstructionSet::new(AND, IZX, 6),
    InstructionSet::new(XXX, IMP, 2),
    InstructionSet::new(XXX, IMP, 8),
    InstructionSet::new(BIT, ZPG, 3),
    InstructionSet::new(AND, ZPG, 3),
    InstructionSet::new(ROL, ZPG, 5),
    InstructionSet::new(XXX, IMP, 5),
    InstructionSet::new(PLP, IMP, 4),
    InstructionSet::new(AND, IMM, 2),
    InstructionSet::new(ROL, IMP, 2),
    InstructionSet::new(XXX, IMP, 2),
    InstructionSet::new(BIT, ABS, 4),
    InstructionSet::new(AND, ABS, 4),
    InstructionSet::new(ROL, ABS, 6),
    InstructionSet::new(XXX, IMP, 6),
    InstructionSet::new(BMI, REL, 2),
    InstructionSet::new(AND, IZY, 5),
    InstructionSet::new(XXX, IMP, 2),
    InstructionSet::new(XXX, IMP, 8),
    InstructionSet::new(NOP, IMP, 4),
    InstructionSet::new(AND, ZPX, 4),
    InstructionSet::new(ROL, ZPX, 6),
    InstructionSet::new(XXX, IMP, 6),
    InstructionSet::new(SEC, IMP, 2),
    InstructionSet::new(AND, ABY, 4),
    InstructionSet::new(NOP, IMP, 2),
    InstructionSet::new(XXX, IMP, 7),
    InstructionSet::new(NOP, IMP, 4),
    InstructionSet::new(AND, ABX, 4),
    InstructionSet::new(ROL, ABX, 7),
    InstructionSet::new(XXX, IMP, 7),
    InstructionSet::new(RTI, IMP, 6),
    InstructionSet::new(EOR, IZX, 6),
    InstructionSet::new(XXX, IMP, 2),
    InstructionSet::new(XXX, IMP, 8),
    InstructionSet::new(NOP, IMP, 3),
    InstructionSet::new(EOR, ZPG, 3),
    InstructionSet::new(LSR, ZPG, 5),
    InstructionSet::new(XXX, IMP, 5),
    InstructionSet::new(PHA, IMP, 3),
    InstructionSet::new(EOR, IMM, 2),
    InstructionSet::new(LSR, IMP, 2),
    InstructionSet::new(XXX, IMP, 2),
    InstructionSet::new(JMP, ABS, 3),
    InstructionSet::new(EOR, ABS, 4),
    InstructionSet::new(LSR, ABS, 6),
    InstructionSet::new(XXX, IMP, 6),
    InstructionSet::new(BVC, REL, 2),
    InstructionSet::new(EOR, IZY, 5),
    InstructionSet::new(XXX, IMP, 2),
    InstructionSet::new(XXX, IMP, 8),
    InstructionSet::new(NOP, IMP, 4),
    InstructionSet::new(EOR, ZPX, 4),
    InstructionSet::new(LSR, ZPX, 6),
    InstructionSet::new(XXX, IMP, 6),
    InstructionSet::new(CLI, IMP, 2),
    InstructionSet::new(EOR, ABY, 4),
    InstructionSet::new(NOP, IMP, 2),
    InstructionSet::new(XXX, IMP, 7),
    InstructionSet::new(NOP, IMP, 4),
    InstructionSet::new(EOR, ABX, 4),
    InstructionSet::new(LSR, ABX, 7),
    InstructionSet::new(XXX, IMP, 7),
    InstructionSet::new(RTS, IMP, 6),
    InstructionSet::new(ADC, IZX, 6),
    InstructionSet::new(XXX, IMP, 2),
    InstructionSet::new(XXX, IMP, 8),
    InstructionSet::new(NOP, IMP, 3),
    InstructionSet::new(ADC, ZPG, 3),
    InstructionSet::new(ROR, ZPG, 5),
    InstructionSet::new(XXX, IMP, 5),
    InstructionSet::new(PLA, IMP, 4),
    InstructionSet::new(ADC, IMM, 2),
    InstructionSet::new(ROR, IMP, 2),
    InstructionSet::new(XXX, IMP, 2),
    InstructionSet::new(JMP, IND, 5),
    InstructionSet::new(ADC, ABS, 4),
    InstructionSet::new(ROR, ABS, 6),
    InstructionSet::new(XXX, IMP, 6),
    InstructionSet::new(BVS, REL, 2),
    InstructionSet::new(ADC, IZY, 5),
    InstructionSet::new(XXX, IMP, 2),
    InstructionSet::new(XXX, IMP, 8),
    InstructionSet::new(NOP, IMP, 4),
    InstructionSet::new(ADC, ZPX, 4),
    InstructionSet::new(ROR, ZPX, 6),
    InstructionSet::new(XXX, IMP, 6),
    InstructionSet::new(SEI, IMP, 2),
    InstructionSet::new(ADC, ABY, 4),
    InstructionSet::new(NOP, IMP, 2),
    InstructionSet::new(XXX, IMP, 7),
    InstructionSet::new(NOP, IMP, 4),
    InstructionSet::new(ADC, ABX, 4),
    InstructionSet::new(ROR, ABX, 7),
    InstructionSet::new(XXX, IMP, 7),
    InstructionSet::new(NOP, IMP, 2),
    InstructionSet::new(STA, IZX, 6),
    InstructionSet::new(NOP, IMP, 2),
    InstructionSet::new(XXX, IMP, 6),
    InstructionSet::new(STY, ZPG, 3),
    InstructionSet::new(STA, ZPG, 3),
    InstructionSet::new(STX, ZPG, 3),
    InstructionSet::new(XXX, IMP, 3),
    InstructionSet::new(DEY, IMP, 2),
    InstructionSet::new(NOP, IMP, 2),
    InstructionSet::new(TXA, IMP, 2),
    InstructionSet::new(XXX, IMP, 2),
    InstructionSet::new(STY, ABS, 4),
    InstructionSet::new(STA, ABS, 4),
    InstructionSet::new(STX, ABS, 4),
    InstructionSet::new(XXX, IMP, 4),
    InstructionSet::new(BCC, REL, 2),
    InstructionSet::new(STA, IZY, 6),
    InstructionSet::new(XXX, IMP, 2),
    InstructionSet::new(XXX, IMP, 6),
    InstructionSet::new(STY, ZPX, 4),
    InstructionSet::new(STA, ZPX, 4),
    InstructionSet::new(STX, ZPY, 4),
    InstructionSet::new(XXX, IMP, 4),
    InstructionSet::new(TYA, IMP, 2),
    InstructionSet::new(STA, ABY, 5),
    InstructionSet::new(TXS, IMP, 2),
    InstructionSet::new(XXX, IMP, 5),
    InstructionSet::new(NOP, IMP, 5),
    InstructionSet::new(STA, ABX, 5),
    InstructionSet::new(XXX, IMP, 5),
    InstructionSet::new(XXX, IMP, 5),
    InstructionSet::new(LDY, IMM, 2),
    InstructionSet::new(LDA, IZX, 6),
    InstructionSet::new(LDX, IMM, 2),
    InstructionSet::new(XXX, IMP, 6),
    InstructionSet::new(LDY, ZPG, 3),
    InstructionSet::new(LDA, ZPG, 3),
    InstructionSet::new(LDX, ZPG, 3),
    InstructionSet::new(XXX, IMP, 3),
    InstructionSet::new(TAY, IMP, 2),
    InstructionSet::new(LDA, IMM, 2),
    InstructionSet::new(TAX, IMP, 2),
    InstructionSet::new(XXX, IMP, 2),
    InstructionSet::new(LDY, ABS, 4),
    InstructionSet::new(LDA, ABS, 4),
    InstructionSet::new(LDX, ABS, 4),
    InstructionSet::new(XXX, IMP, 4),
    InstructionSet::new(BCS, REL, 2),
    InstructionSet::new(LDA, IZY, 5),
    InstructionSet::new(XXX, IMP, 2),
    InstructionSet::new(XXX, IMP, 5),
    InstructionSet::new(LDY, ZPX, 4),
    InstructionSet::new(LDA, ZPX, 4),
    InstructionSet::new(LDX, ZPY, 4),
    InstructionSet::new(XXX, IMP, 4),
    InstructionSet::new(CLV, IMP, 2),
    InstructionSet::new(LDA, ABY, 4),
    InstructionSet::new(TSX, IMP, 2),
    InstructionSet::new(XXX, IMP, 4),
    InstructionSet::new(LDY, ABX, 4),
    InstructionSet::new(LDA, ABX, 4),
    InstructionSet::new(LDX, ABY, 4),
    InstructionSet::new(XXX, IMP, 4),
    InstructionSet::new(CPY, IMM, 2),
    InstructionSet::new(CMP, IZX, 6),
    InstructionSet::new(NOP, IMP, 2),
    InstructionSet::new(XXX, IMP, 8),
    InstructionSet::new(CPY, ZPG, 3),
    InstructionSet::new(CMP, ZPG, 3),
    InstructionSet::new(DEC, ZPG, 5),
    InstructionSet::new(XXX, IMP, 5),
    InstructionSet::new(INY, IMP, 2),
    InstructionSet::new(CMP, IMM, 2),
    InstructionSet::new(DEX, IMP, 2),
    InstructionSet::new(XXX, IMP, 2),
    InstructionSet::new(CPY, ABS, 4),
    InstructionSet::new(CMP, ABS, 4),
    InstructionSet::new(DEC, ABS, 6),
    InstructionSet::new(XXX, IMP, 6),
    InstructionSet::new(BNE, REL, 2),
    InstructionSet::new(CMP, IZY, 5),
    InstructionSet::new(XXX, IMP, 2),
    InstructionSet::new(XXX, IMP, 8),
    InstructionSet::new(NOP, IMP, 4),
    InstructionSet::new(CMP, ZPX, 4),
    InstructionSet::new(DEC, ZPX, 6),
    InstructionSet::new(XXX, IMP, 6),
    InstructionSet::new(CLD, IMP, 2),
    InstructionSet::new(CMP, ABY, 4),
    InstructionSet::new(NOP, IMP, 2),
    InstructionSet::new(XXX, IMP, 7),
    InstructionSet::new(NOP, IMP, 4),
    InstructionSet::new(CMP, ABX, 4),
    InstructionSet::new(DEC, ABX, 7),
    InstructionSet::new(XXX, IMP, 7),
    InstructionSet::new(CPX, IMM, 2),
    InstructionSet::new(SBC, IZX, 6),
    InstructionSet::new(NOP, IMP, 2),
    InstructionSet::new(XXX, IMP, 8),
    InstructionSet::new(CPX, ZPG, 3),
    InstructionSet::new(SBC, ZPG, 3),
    InstructionSet::new(INC, ZPG, 5),
    InstructionSet::new(XXX, IMP, 5),
    InstructionSet::new(INX, IMP, 2),
    InstructionSet::new(SBC, IMM, 2),
    InstructionSet::new(NOP, IMP, 2),
    InstructionSet::new(SBC, IMP, 2),
    InstructionSet::new(CPX, ABS, 4),
    InstructionSet::new(SBC, ABS, 4),
    InstructionSet::new(INC, ABS, 6),
    InstructionSet::new(XXX, IMP, 6),
    InstructionSet::new(BEQ, REL, 2),
    InstructionSet::new(SBC, IZY, 5),
    InstructionSet::new(XXX, IMP, 2),
    InstructionSet::new(XXX, IMP, 8),
    InstructionSet::new(NOP, IMP, 4),
    InstructionSet::new(SBC, ZPX, 4),
    InstructionSet::new(INC, ZPX, 6),
    InstructionSet::new(XXX, IMP, 6),
    InstructionSet::new(SED, IMP, 2),
    InstructionSet::new(SBC, ABY, 4),
    InstructionSet::new(NOP, IMP, 2),
    InstructionSet::new(XXX, IMP, 7),
    InstructionSet::new(NOP, IMP, 4),
    InstructionSet::new(SBC, ABX, 4),
    InstructionSet::new(INC, ABX, 7),
    InstructionSet::new(XXX, IMP, 7),
];
